[package]
name = "twentyfour"
version = "0.1.0"
authors = ["Aaron McLeod <aaron.g.mcleod@gmail.com>"]

[dependencies]
read_input = { path = "../read_input" }
astar = { path = "../astar" }
permutohedron = "0.2.4"